plugins:
  - jekyll-relative-links
title: TA Applications at Carnegie Mellon University
description: Learn more about the TA application process at CMU.
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-slate
